apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: {{ .Values.containerName }}
          image: {{ .Values.containerImage }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
          stdin: true
          stdinOnce: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
          env:
            - name: GIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: username
            - name: GIT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretName }}
                  key: token
          volumeMounts:
            - name: {{ .Values.volumeName }}
              mountPath: {{ .Values.mountPath }}
      volumes:
        - name: {{ .Values.volumeName }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Values.secretProviderClassName }}
